services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: senhasupersecreta
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress1
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app-network

  wordpress2:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress2
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - app-network

  wordpress3:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress3
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html 
    networks:
      - app-network

  nginx:
    image: nginx:1.19.0
    container_name: nginx_lb
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - wordpress_data:/usr/share/nginx/html 
    networks:
      - app-network

  locust:
      image: grubykarol/locust:latest
      container_name: locust_tester
      ports:
        - "8089:8089"
      environment:
        - ATTACKED_HOST=http://nginx
        - LOCUST_FILE=/locust/scenario3.py
      volumes:
        - ./locust-scripts:/locust
      networks:
        - app-network
      depends_on:
        - nginx
      restart: unless-stopped

volumes:
  db_data:
  wordpress_data: 

networks:
  app-network:
    driver: bridge